-- AlterTable
ALTER TABLE "media" ADD COLUMN     "averageRating" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalReviews" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "review" ALTER COLUMN "rating" SET DATA TYPE DOUBLE PRECISION;
